server:
  port: 8083
spring:
  application:
    name: nacos-cunsumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoint:
    web:
      exposure:
          include: '*'

